language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/doc.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "CkUn7y/EBwyWt/wekAEDshxw0YsywkDGU7wZ8Zl2iUNNMeqUjgjcJ/JUdMgwXybCULBz8Fj2+c9pFk+Whf+zpRENSSutPURYjvNLaE4yk3C/ga4dal6jiFNWHRsjNjgMHaREmQa4IQSJNr2hZwa+jEsfC3b0jtkmpj+VQIxoE5yba0cWZzmjaAKcHVXBk4C9Mv0ZCAK8x6OG/I97d5X8+0eM+0cf6nCavPdnw4ahwrRNVKbBcwPe/4u6FTOcpJ1gboZIbcrUgO3EkCBNhkn+yr5y8XFAI9ywWj94ZT2WzeJD988mpA518WpD9b32D0guuPJsq6h6PZY9SebQwyBLV15YqZkWS39n8mNhctr8OBcsNuz3gkfIbF4zvdkoXdcB8eZbVsN1FRtj2SqeOlGje9/gB9BPNF0fpo+bUZkF/XK1xwETKmRY/WH329Y7Obdi3zuFbBnywMPy8iMD3xD1VNbmcLoH8NV4dtxF03i1Cpsp9liGdMGNiP7Caeo5UFlw96TKHBU5wsWLXOlsMmtwMRSP/076p58pBHVZaQvsNZ8gcJXhvlLrwrWeMmbHgdkhSOvboGDR0c2XtzjSuxhLOGUwc7IFLF1U7hjeGX1j7Cdf2h/nsFHHmwR48xYiwQS5BjWKuxaILHmgvGJ79ds1JrZUUAAZgVilJW/FBg0wsQ8="
