language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/doc.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "HclOGt5aEezZpvUqu2pi1SrbZtCvFBrN4CPOrAY3IRLj8HZyyIr6WL5oOyu19d0EgZwYVjsXS/Za4MwNCC5BRJv9XKsldifYYEY5Giz/OqhH64cuE2vfm4w3Qe9g/oP/ku/6s0jVGIOrBo1N8GGAYrXVH33aOSc12+Ewvf4ybCwYPLbFyjW9d/ZGbtpHp5/WhemwORLV0H1h8AJWYKXqH+FwyhfEYz+yAwgtywehcleGqcOoy3p1/wpAPwaMO83KZAAKY6SRi5yGvBgbRA4eyrEV+jpDfjYsybt6D7A12cc9nYkZuPryVFiHTDA4W2cC1vI7H8Mgi65+ZEWx2dplOLHtqUqj7hdhLVtgiLBFXpQQ+iJkS3rYifuPqGC8NZZSwiTnXizRvJkmRua8LaI8V+65YgXHqwQHaYbMnVoBjxoH0ltGGpo/82taC5ujjKjLqE2Jp2JWps6jfXGcgJqyVqW8n+wk1uaXt0FQmvqHe9k1O8a5/q6ngLEfDUeBXzV4SWjZdVTy4+XY/2D9JreZcndDt9Kp1ixKpumokgdpeSyis+QD82GC39Z76Q+rNTJ3oXeV3JghvTNBr1ySwXdbTmVid6tatN3fp3oqOrrI/EmuxyszXIJWf7xH/2AhXpDEuUMO62y1Q3B96+aWYIKIcYLN441+Vbg0RVJ7SVtMqNw="
env:
  secure: "WgGn1D8ryENUfY8BCuiUeKOVcnHim62ScFEQM/4ZNVSCAihy4h8K6clz+psLmHiZSshIVK7i67DkDhAEunR3+FPY2AK5j4HxOZSfo31BKSda0phWFDxdr40J8uZBSkND5E3sU+4+H2usCoKQP+9mxyGs2ilNbUDX34gXTDQKO5DE0mUMXXZGXPmz8G1I9vEgH5COpAfFBwMXmYAqGmW+6FCunHrHzf38BDu6oinDdu4vjZZyKc/eGL9MKuafIODqSQ90KNNdJNXNE7ZGOMBJNqJnfnLoayLFT2gnGW6tJawHVJkPhZoR+MKZZwxdQ8Lj6lWPb8i5dV8CeLYSES+agxjG76ABoU4P4opDzXt9FL94fr5xxCCovMMCftMaUOyRGx4RJrwkbKVrBtVjVjDtNRKOXrffAU3FMfp/DqSg8XaKx25knDy9GeRgky2JX8uRp1U9oknGOajFOS1gHWI8cY0ZB3XwXtKaqwemfSN4LvFvDpt8A9icWioX/vXqd0UQgsBzddaauRgHi6eA7qohjqcMmRGy3Y59EYxQrfUJ6lEqLAHNV/C8Mbuq4RqksITdDxpleHwz+7H4jAVSr1s1UOfBOXFu6ucCjTAygH4QEVxdyq7qSeGsM+jLrK1wPAglnv76Fiq9787HzV7U8Z7vaKPGE+4g9xyIunMliQKLaHE="
